# This is a basic workflow to help you get started with Actions

name: Build and Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: "wasm-pack"
        run: wasm-pack build --target web --out-name wasm --out-dir ./static
        
      - uses: actions/upload-artifact@master
        with:
          name: static
          path: ./static/
        
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - uses: actions/download-artifact@v2
        with:
          name: static
      
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd ./static
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy github pages'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # this might change depending on whether you are publishing a site for a normal repo or a user/organization repo
          branch: gh-pages
          force: true
          directory: ./static
